rules:
  # Avoid dynamic code execution
  - id: js.no-eval-or-function-constructor
    message: Avoid eval() and Function constructor; use safe alternatives
    languages: [javascript, typescript]
    severity: WARNING
    pattern-either:
      - pattern: eval($X)
      - pattern: new Function($ARGS, ...)

  # Dangerous process execution
  - id: node.no-child-process-exec
    message: Avoid child_process.exec/execSync; prefer spawn with args and sanitized inputs
    languages: [javascript, typescript]
    severity: WARNING
    pattern-either:
      - pattern: child_process.exec($CMD)
      - pattern: exec($CMD)
      - pattern: child_process.execSync($CMD)
      - pattern: execSync($CMD)

  # Insecure HTTP URL usage in network calls
  - id: net.no-http-in-fetch-or-axios
    message: Use HTTPS, not HTTP, for network calls
    languages: [javascript, typescript]
    severity: WARNING
    pattern-either:
      - pattern: fetch("http://...", ...)
      - pattern: axios.get("http://...", ...)
      - pattern: axios.post("http://...", ...)
      - pattern: axios.put("http://...", ...)
      - pattern: axios.delete("http://...", ...)

  # GraphQL: avoid enabling introspection in production configs
  - id: graphql.no-introspection-true
    message: Disable GraphQL introspection in production
    languages: [javascript, typescript]
    severity: WARNING
    pattern-regex: '(?i)introspection\s*:\s*true'

  # JWT hardcoded secret in sign
  - id: jwt.no-hardcoded-secret
    message: Avoid hardcoded JWT secrets in code
    languages: [javascript, typescript]
    severity: WARNING
    patterns:
      - pattern: jwt.sign($PAYLOAD, $SECRET, ...)
      - metavariable-pattern:
          metavariable: $SECRET
          pattern: "'...'|\"...\""

  # CORS allow-all
  - id: cors.no-wildcard-origin
    message: Avoid CORS wildcard origin in production
    languages: [javascript, typescript]
    severity: WARNING
    pattern-regex: "cors\\(\\{\\s*origin:\\s*['\\\"]\\*['\\\"]"

  # Disallow NODE_TLS_REJECT_UNAUTHORIZED overrides
  - id: tls.no-disable-verification
    message: Do not disable TLS verification (NODE_TLS_REJECT_UNAUTHORIZED)
    languages: [javascript, typescript]
    severity: WARNING
    pattern-regex: 'NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*0'

  # Paths filters to reduce noise
  - id: meta.paths-filter
    message: "(meta) paths filter"
    languages: [generic]
    severity: INFO
    paths:
      exclude:
        - node_modules/**
        - coverage/**
        - Whot2Watch-docs/**
        - whot2watch-docs-full/**
        - **/*.md
