/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/admin/refresh/tmdb/{tmdbId}': {
    /** Admin refresh by TMDB ID (enrich imdbId and ratings; reindex) */
    post: {
      parameters: {
        path: {
          tmdbId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': {
              ok?: boolean;
              imdbId?: string | null;
              ratingsUpserts?: number;
            };
          };
        };
        /** @description unauthorized */
        401: {
          content: never;
        };
        /** @description forbidden */
        403: {
          content: never;
        };
        /** @description not found */
        404: {
          content: never;
        };
      };
    };
  };
  '/admin/refresh/imdb/{imdbId}': {
    /** Admin refresh by IMDB ID (ratings upsert; reindex) */
    post: {
      parameters: {
        path: {
          imdbId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': {
              ok?: boolean;
              ratingsUpserts?: number;
            };
          };
        };
        /** @description unauthorized */
        401: {
          content: never;
        };
        /** @description forbidden */
        403: {
          content: never;
        };
        /** @description not found */
        404: {
          content: never;
        };
      };
    };
  };
  '/picks': {
    /** Get daily picks for a profile */
    get: {
      parameters: {
        query: {
          profileId: string;
          limit?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['Recommendation'][];
          };
        };
      };
    };
  };
  '/search': {
    /** Search titles */
    get: {
      parameters: {
        query?: {
          q?: string;
          region?: components['schemas']['Region'];
          providerIn?: components['schemas']['Provider'][];
          runtimeLt?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': {
              items?: components['schemas']['Title'][];
              nextCursor?: string;
            };
          };
        };
      };
    };
  };
  '/availability/{titleId}': {
    /** Get availability for a title */
    get: {
      parameters: {
        query?: {
          region?: components['schemas']['Region'];
          services?: components['schemas']['Provider'][];
        };
        path: {
          titleId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['Availability'][];
          };
        };
      };
    };
  };
  '/lists': {
    /** List user lists */
    get: {
      parameters: {
        query: {
          profileId: string;
          visibility?: 'PRIVATE' | 'FRIENDS' | 'PUBLIC' | 'COLLAB';
          first?: number;
          after?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': {
              items?: components['schemas']['List'][];
              nextCursor?: string;
            };
          };
        };
      };
    };
  };
  '/alerts': {
    /** List alerts */
    get: {
      parameters: {
        query: {
          profileId: string;
          status?: 'ACTIVE' | 'FIRED' | 'CANCELLED';
          first?: number;
          after?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': {
              items?: Record<string, never>[];
              nextCursor?: string;
            };
          };
        };
      };
    };
  };
  '/subscriptions': {
    /** List subscriptions */
    get: {
      parameters: {
        query: {
          profileId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['Subscription'][];
          };
        };
      };
    };
  };
  '/group-sessions': {
    /** List group sessions */
    get: {
      parameters: {
        query?: {
          hostProfileId?: string;
          participantProfileId?: string;
          status?: 'open' | 'locked' | 'closed';
          first?: number;
          after?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': {
              items?: components['schemas']['GroupSession'][];
              nextCursor?: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @enum {string} */
    Region: 'US' | 'CA' | 'GB' | 'AU' | 'IN';
    /** @enum {string} */
    Provider:
      | 'NETFLIX'
      | 'AMAZON_PRIME_VIDEO'
      | 'DISNEY_PLUS'
      | 'HULU'
      | 'MAX'
      | 'APPLE_TV_PLUS'
      | 'PARAMOUNT_PLUS'
      | 'PEACOCK'
      | 'CRUNCHYROLL'
      | 'TUBI'
      | 'OTHER';
    Availability: {
      service?: components['schemas']['Provider'];
      region?: components['schemas']['Region'];
      /** @enum {string} */
      offerType?: 'SUBSCRIPTION' | 'RENT' | 'BUY' | 'FREE';
      deepLink?: string;
      /** Format: date-time */
      lastSeenAt?: string;
    };
    Title: {
      /** Format: uuid */
      id?: string;
      name?: string;
      /** @enum {string} */
      type?: 'MOVIE' | 'SHOW';
      releaseYear?: number;
      runtimeMin?: number;
      genres?: string[];
      moods?: string[];
      posterUrl?: string;
      backdropUrl?: string;
      overview?: string;
      voteAverage?: number;
      popularity?: number;
      availability?: components['schemas']['Availability'][];
    };
    Recommendation: {
      /** Format: uuid */
      id?: string;
      title?: components['schemas']['Title'];
      score?: number;
      reason?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    Subscription: {
      /** Format: uuid */
      id?: string;
      service?: components['schemas']['Provider'];
      region?: components['schemas']['Region'];
      active?: boolean;
      /** Format: date-time */
      createdAt?: string;
    };
    List: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      ownerProfileId?: string;
      name?: string;
      /** @enum {string} */
      visibility?: 'PRIVATE' | 'FRIENDS' | 'PUBLIC' | 'COLLAB';
      description?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    GroupSession: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      hostProfileId?: string;
      name?: string;
      constraints?: Record<string, never>;
      /** @enum {string} */
      status?: 'open' | 'locked' | 'closed';
      /** Format: date-time */
      createdAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
